 local menue0e4fc6213e8b3593495a7260c3a4c2e = {
     {"Workrave", "workrave", "/usr/share/icons/hicolor/16x16/apps/workrave.png" },
 }

 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Application Finder", "xfce4-appfinder", "/usr/share/icons/gnome/16x16/actions/edit-find.png" },
     {"DB Browser for SQLite", "sqlitebrowser ", "/usr/share/icons/hicolor/256x256/apps/sqlitebrowser.png" },
     {"Files", "nautilus --new-window ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Nautilus.png" },
     {"GVim", "gvim -f ", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
     {"HP Device Manager", "hp-toolbox", "///usr/share/hplip/data/images/128x128/hp_logo.png" },
     {"Mark My Words", "mark-my-words ", "/usr/share/pixmaps/mark-my-words.svg" },
     {"Redshift", "redshift-gtk"},
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"SLADE", "slade ", "/usr/share/icons/hicolor/16x16/apps/slade.png" },
     {"Screenkey", "screenkey", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-keyboard-shortcuts.png" },
     {"Sublime Text", "subl ", "/usr/share/icons/hicolor/16x16/apps/sublime-text.png" },
     {"Text Editor", "gedit ", "/usr/share/icons/hicolor/16x16/apps/gedit.png" },
     {"Winetricks", "winetricks --gui"},
     {"Workrave", "workrave", "/usr/share/icons/hicolor/16x16/apps/workrave.png" },
     {"bpython", "xterm -e /usr/bin/bpython", "/usr/share/pixmaps/bpython.png" },
     {"bpython2", "xterm -e /usr/bin/bpython2", "/usr/share/pixmaps/bpython2.png" },
     {"compton", "compton --xrender-sync-fence", "/usr/share/icons/hicolor/48x48/apps/compton.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
     {"ipython2", "xterm -e ipython2", "/usr/share/pixmaps/ipython2.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"GNU Octave", "/usr/bin/octave --force-gui ", "/usr/share/icons/hicolor/16x16/apps/octave.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"PlayOnLinux", "playonlinux", "///usr/share/playonlinux/etc/playonlinux.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Blender", "blender ", "/usr/share/icons/hicolor/16x16/apps/blender.png" },
     {"Deepin Screenshot", "deepin-screenshot --icon"},
     {"Dia Diagram Editor", "dia ", "/usr/share/icons/hicolor/16x16/apps/dia.png" },
     {"DjView4", "djview4 ", "/usr/share/icons/hicolor/32x32/mimetypes/djvulibre-djview4.png" },
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"E-book Viewer", "ebook-viewer --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"FontForge", "fontforge ", "/usr/share/icons/hicolor/16x16/apps/fontforge.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Geeqie", "geeqie -r ", "/usr/share/pixmaps/geeqie.png" },
     {"Gpick", "gpick", "/usr/share/icons/hicolor/48x48/apps/gpick.png" },
     {"LRF Viewer", "lrfviewer ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"MeshLab", "meshlab ", "///usr/share/pixmaps/meshlab.png" },
     {"Scan Tailor", "scantailor ", "///usr/share/icons/hicolor/scalable/apps/scantailor.svg" },
     {"gThumb", "gthumb ", "/usr/share/icons/hicolor/16x16/apps/gthumb.png" },
     {"llpp", "llpp "},
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Browse Mirrored Websites", "webhttrack browse", "/usr/share/icons/hicolor/16x16/apps/httrack.png" },
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Corebird", "corebird", "/usr/share/icons/hicolor/16x16/apps/corebird.png" },
     {"Dropbox", "dropbox", "/usr/share/pixmaps/dropbox.png" },
     {"Electronic WeChat", "/usr/bin/electronic-wechat", "///usr/share/electronic-wechat/assets/icon.png" },
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Keybase", "run_keybase", "/usr/share/icons/hicolor/16x16/apps/keybase.png" },
     {"Links", "xlinks -g", "/usr/share/pixmaps/links_32x32.xpm" },
     {"MEGASync", "megasync", "/usr/share/icons/hicolor/16x16/apps/mega.png" },
     {"Navicat Lite", "/usr/bin/navicat", "///opt/navicat/Navicat/help/img/icon_navicat.png" },
     {"Opera", "opera ", "/usr/share/icons/hicolor/16x16/apps/opera.png" },
     {"Qtransmission Bittorrent Client", "transmission-qt ", "/usr/share/pixmaps/transmission-qt.png" },
     {"Rambox", "rambox -- ", "/usr/share/pixmaps/rambox.png" },
     {"Skype", "skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"TeamViewer 12", "/opt/teamviewer/tv_bin/script/teamviewer", "/usr/share/icons/hicolor/48x48/apps/teamviewer.png" },
     {"Telegram Desktop", "/usr/bin/telegram-desktop -- ", "/usr/share/icons/hicolor/16x16/apps/telegram-desktop.png" },
     {"TigerVNC Viewer", "/usr/bin/vncviewer", "/usr/share/icons/hicolor/16x16/apps/tigervnc.png" },
     {"WebHTTrack Website Copier", "webhttrack", "/usr/share/icons/hicolor/16x16/apps/httrack.png" },
     {"Wicd", "/usr/bin/wicd-client", "/usr/share/icons/hicolor/16x16/apps/wicd-gtk.png" },
     {"Wireshark (GTK+)", "wireshark-gtk ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Calibre", "calibre --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-gui.png" },
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"Edit E-book", "ebook-edit --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-ebook-edit.png" },
     {"FBReader", "FBReader ", "/usr/share/pixmaps/FBReader.png" },
     {"Foxit Reader", "foxitreader ", "/usr/share/pixmaps/foxitreader.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Master PDF Editor", "/opt/master-pdf-editor-4/masterpdfeditor4 ", "///opt/master-pdf-editor-4/masterpdfeditor4.png" },
     {"llpp", "llpp "},
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Arduino IDE", "arduino ", "/usr/share/icons/hicolor/16x16/apps/arduino.png" },
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Cppcheck", "cppcheck-gui"},
     {"DB Browser for SQLite", "sqlitebrowser ", "/usr/share/icons/hicolor/256x256/apps/sqlitebrowser.png" },
     {"Electron", "electron ", "/usr/share/pixmaps/electron.png" },
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/16x16/apps/fluid.png" },
     {"Java Mission Control", "/usr/lib/jvm/java-8-jdk/bin/jmc", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"Java Monitoring and Management Console", "/usr/lib/jvm/java-8-jdk/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"Java VisualVM", "/usr/lib/jvm/java-8-jdk/bin/jvisualvm", "/usr/share/icons/hicolor/16x16/apps/sun-java-jdk8.png" },
     {"Meld", "meld ", "/usr/share/icons/hicolor/16x16/apps/meld.png" },
     {"MySQL Workbench", "mysql-workbench ", "/usr/share/icons/hicolor/16x16/apps/mysql-workbench.png" },
     {"NVIDIA Visual Profiler", "/opt/cuda/bin/nvvp", "///opt/cuda/libnvvp/icon.xpm" },
     {"Nsight Eclipse Edition", "/opt/cuda/bin/nsight", "///opt/cuda/libnsight/icon.xpm" },
     {"OpenJDK 1.7.0 Monitoring & Management Console", "_BINDIR_/jconsole"},
     {"OpenJDK 1.7.0 Policy Tool", "_BINDIR_/policytool"},
     {"Qt Assistant", "assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Creator", "qtcreator ", "/usr/share/icons/hicolor/16x16/apps/QtProject-qtcreator.png" },
     {"Qt Designer", "designer", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"Zeal", "zeal ", "/usr/share/icons/hicolor/16x16/apps/zeal.png" },
     {"bpython", "xterm -e /usr/bin/bpython", "/usr/share/pixmaps/bpython.png" },
     {"bpython2", "xterm -e /usr/bin/bpython2", "/usr/share/pixmaps/bpython2.png" },
     {"gitg", "gitg --no-wd ", "/usr/share/icons/hicolor/16x16/apps/gitg.png" },
     {"haroopad", "haroopad", "/usr/share/icons/hicolor/16x16/apps/haroopad.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
     {"ipython2", "xterm -e ipython2", "/usr/share/pixmaps/ipython2.png" },
 }

 local menu80d754c83abbbd4ef5d150904efcc86c = {
     {"R", "xterm -e R", "///usr/share/pixmaps/r.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Audacity", "env UBUNTU_MENUPROXY=0 audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Banshee Media Player", "banshee --redirect-log --play-enqueued ", "/usr/share/icons/hicolor/16x16/apps/media-player-banshee.png" },
     {"Cheese", "cheese", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Cheese.png" },
     {"Deepin Movie", "deepin-movie "},
     {"EasyTAG", "easytag ", "/usr/share/icons/hicolor/16x16/apps/easytag.png" },
     {"FFADO Mixer", "ffado-mixer", "/usr/share/pixmaps/ffado.png" },
     {"HDSPConf", "hdspconf", "/usr/share/pixmaps/hdspconf.png" },
     {"HDSPMixer", "hdspmixer", "/usr/share/pixmaps/hdspmixer.png" },
     {"Kdenlive", "kdenlive ", "/usr/share/icons/hicolor/16x16/apps/kdenlive.png" },
     {"MuseScore 2", "mscore ", "/usr/share/icons/hicolor/64x64/apps/mscore.png" },
     {"NetEase Cloud Music", "netease-cloud-music "},
     {"Pitivi", "pitivi ", "/usr/share/icons/hicolor/16x16/apps/pitivi.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"QtAV Player", "Player -f "},
     {"QtAV QML Player", "QMLPlayer -f "},
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"gtk-recordMyDesktop", "gtk-recordMyDesktop", "/usr/share/pixmaps/gtk-recordmydesktop.png" },
     {"mpv Media Player", "mpv --player-operation-mode=pseudo-gui -- ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"Fcitx", "fcitx", "/usr/share/icons/hicolor/16x16/apps/fcitx.png" },
     {"Files", "pantheon-files ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Hardware Locality lstopo", "lstopo"},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"MEGASync", "megasync", "/usr/share/icons/hicolor/16x16/apps/mega.png" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"ROXTerm", "roxterm"},
     {"Sakura", "sakura", "/usr/share/pixmaps/terminal-tango.svg" },
     {"Termite", "termite", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Thunar File Manager", "thunar ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"UNetbootin", "/usr/bin/unetbootin", "/usr/share/icons/hicolor/16x16/apps/unetbootin.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Vifm", "xterm -e vifm ", "/usr/share/pixmaps/vifm.png" },
     {"WinUSB", "winusbgui", "/usr/share/pixmaps/winusbgui-icon.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Xfce Terminal", "xfce4-terminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Xsensors", "xsensors", "/usr/share/pixmaps/xsensors.png" },
     {"ranger", "xterm -e ranger", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
 }

xdgmenu = {
    {"Accessibility", menue0e4fc6213e8b3593495a7260c3a4c2e},
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Science & Math", menu80d754c83abbbd4ef5d150904efcc86c},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

return xdgmenu
