#!/bin/bash -e

files=$1
echo $1
read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
	git filter-branch --force --index-filter "git rm --cached --ignore-unmatch -r $1" --prune-empty --tag-name-filter cat -- --all

	git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin

	rm -rf .git/refs/original/

	git reflog expire --expire=now --all

	git gc --prune=now
	git gc --aggressive --prune=now
fi
