#!/usr/bin/env python
import sys
import subprocess
import time
import os
import argparse


def write(b: bytes):
    os.write(1, b)


def write_tmux_passthrough(b: bytes):
    write(b'\x1bPtmux;')
    write(b.replace(b'\x1b', b'\x1b\x1b'))
    write(b'\x1b\\')


def tmux_passthrough(buf: bytes):
    curr = 0
    while True:
        start = buf.find(b'\x1b', curr)
        if start < 0:
            break
        end = buf.find(b'\x1b\\', start + 1)
        if end < 0:
            break
        write(buf[curr:start])
        write_tmux_passthrough(buf[start:end + 2])
        curr = end + 2


def clear_kitty():
    sys.stdout.buffer.write(b'\033Ptmux;\033' + b'\033_Ga=d,d=A\033\033\\' + b'\033\\')


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    cmds = parser.add_subparsers(title="subcommands", dest="command")
    p = cmds.add_parser("kittyimg",
                        help="Show an image using kitty protocol. Works OKish in tmux.")
    p.add_argument("input", help="image file")
    p.add_argument("--ttl", type=int, default=3, help="time to clear the image, if in tmux")
    p = cmds.add_parser("fallthrough", help="tmux-fallthrough for stdin. for debugging.")
    p = cmds.add_parser("clear", help="clear kitty image")

    args = parser.parse_args()

    if args.command == "fallthrough":
        buf = sys.stdin.buffer.read()
        tmux_passthrough(buf)
    elif args.command == "kittyimg":
        fname = args.input
        if "TMUX" not in os.environ:
            cmd = f'timg -C -pk "{fname}"'
            os.system(cmd)
        else:
            cmd = f'timg -C -g x100 -pk "{fname}"'
            buf = subprocess.check_output(cmd, shell=True)
            write_tmux_passthrough(buf)
            if args.ttl > 0:
                time.sleep(args.ttl)
                clear_kitty()
    elif args.command == "clear":
        clear_kitty()
