[user]
name = "Yuxin Wu"

[ui]
editor = "nvim"

[aliases]
#sl = ["log", "-r", "main:: ~ (remote_branches() ~ branches())", "--no-pager", "--reversed"]
# trunk: https://martinvonz.github.io/jj/v0.10.0/revsets/#built-in-aliases
sl = ["log", "-r", "trunk():: ~ (remote_branches() ~ branches()) | (@..branches())", "--no-pager", "--reversed"]

[git]
# https://martinvonz.github.io/jj/v0.10.0/config/#automatic-local-branch-creation
auto-local-branch = false


[templates]
log = 'my_log_compact'

[template-aliases]
# Remove author.
my_log_compact = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        format_short_change_id_with_hidden_and_divergent_info(self),
        format_timestamp(committer.timestamp()),
        branches,
        tags,
        working_copies,
        git_head,
        format_short_commit_id(commit_id),
        if(conflict, label("conflict", "conflict")),
      ) ++ "\n",
      separate(" ",
        if(empty, label("empty", "(empty)")),
        if(description,
          description.first_line(),
          label(if(empty, "empty"), description_placeholder),
        ),
      ) ++ "\n",
    ),
  )
)
'''

[snapshot]
max-new-file-size = "10MiB"
