 local menue0e4fc6213e8b3593495a7260c3a4c2e = {
     {"KSimond", "ksimond  -caption \"KSimond\"", "/usr/share/icons/hicolor/16x16/apps/ksimond.png" },
     {"SSC", "ssc  -caption \"SSC\"", "/usr/share/icons/hicolor/16x16/apps/ssc.png" },
     {"SSCd", "xterm -e sscd  -caption \"SSCd\""},
     {"Sam", "sam  -caption \"Sam\"", "/usr/share/icons/hicolor/16x16/apps/sam.png" },
     {"Simon", "simon", "/usr/share/icons/hicolor/16x16/apps/simon.png" },
     {"Simond", "xterm -e simond  -caption \"Simond\"", "/usr/share/icons/hicolor/16x16/apps/simond.png" },
 }

 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"7-Zip FM", "7zFM", "/usr/share/icons/hicolor/32x32/apps/p7zip.png" },
     {"Adie", "adie", "/usr/share/pixmaps/adie.png" },
     {"Afaras", "afaras  -caption \"Afaras\"", "/usr/share/icons/hicolor/16x16/apps/afaras.png" },
     {"Akonaditray", "akonaditray", "/usr/share/icons/hicolor/22x22/apps/akonaditray.png" },
     {"Application Finder", "xfce4-appfinder", "/usr/share/icons/gnome/16x16/actions/gtk-find.png" },
     {"Archive Manager", "file-roller ", "/usr/share/icons/hicolor/16x16/apps/file-roller.png" },
     {"FOX Calculator", "calculator", "/usr/share/pixmaps/calculator.png" },
     {"File Manager PCManFM", "pcmanfm ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"Filelight", "filelight ", "/usr/share/icons/hicolor/16x16/apps/filelight.png" },
     {"Font Viewer", "gnome-font-viewer ", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-font.png" },
     {"GTKWave", "gtkwave", "/usr/share/icons/gnome/16x16/mimetypes/gtkwave.png" },
     {"Hopper Disassembler", "/usr/bin/hopper", "/usr/share/icons/hicolor/16x16/apps/hopper-disassembler.png" },
     {"IPython Qt console", "ipython qtconsole", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"IPython2 Qt console", "ipython2 qtconsole", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"KSimond", "ksimond  -caption \"KSimond\"", "/usr/share/icons/hicolor/16x16/apps/ksimond.png" },
     {"Keyboard", "matchbox-keyboard", "/usr/share/pixmaps/matchbox-keyboard.png" },
     {"PDF Editor", "pdfedit", "/usr/share/pixmaps/pdfedit.png" },
     {"Qemu Launcher", "qemu-launcher"},
     {"SSC", "ssc  -caption \"SSC\"", "/usr/share/icons/hicolor/16x16/apps/ssc.png" },
     {"SSCd", "xterm -e sscd  -caption \"SSCd\""},
     {"Sam", "sam  -caption \"Sam\"", "/usr/share/icons/hicolor/16x16/apps/sam.png" },
     {"ScreenRuler", "/usr/bin/screenruler", "///usr/share/pixmaps/screenruler.png" },
     {"Screenshot", "xfce4-screenshooter", "/usr/share/icons/hicolor/48x48/apps/applets-screenshooter.png" },
     {"Simon", "simon", "/usr/share/icons/hicolor/16x16/apps/simon.png" },
     {"Simond", "xterm -e simond  -caption \"Simond\"", "/usr/share/icons/hicolor/16x16/apps/simond.png" },
     {"SpaceFM File Search", "spacefm --find-files ", "/usr/share/icons/hicolor/48x48/apps/spacefm-find.png" },
     {"StarDict", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"Sublime Text", "subl ", "/usr/share/icons/hicolor/16x16/apps/sublime_text.png" },
     {"Xfi", "xfi", "/usr/share/pixmaps/xfi.png" },
     {"Xfp", "xfp", "/usr/share/pixmaps/xfp.png" },
     {"Xfv", "xfv", "/usr/share/pixmaps/xfv.png" },
     {"Xfw", "xfw", "/usr/share/pixmaps/xfw.png" },
     {"Xournal", "xournal "},
     {"bpython", "xterm -e /usr/bin/bpython"},
     {"bpython2", "xterm -e /usr/bin/bpython2"},
     {"gedit", "gedit ", "/usr/share/icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"ipython", "xterm -e ipython", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"ipython2", "xterm -e ipython2", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"medit", "medit ", "/usr/share/icons/hicolor/48x48/apps/medit.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"Klavaro", "klavaro", "/usr/share/icons/hicolor/16x16/apps/klavaro.png" },
     {"R", "xterm -e R", "///usr/share/pixmaps/r.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"Block Attack!", "blocks", "/usr/share/icons/hicolor/32x32/apps/blocks.png" },
     {"Checkers", "checkers", "/usr/share/icons/hicolor/32x32/apps/checkers.png" },
     {"Dosbox", "dosbox", "/usr/share/pixmaps/dosbox.png" },
     {"KMines", "kmines -caption KMines", "/usr/share/icons/hicolor/16x16/apps/kmines.png" },
     {"KSudoku", "ksudoku  -caption KSudoku", "/usr/share/icons/hicolor/16x16/apps/ksudoku.png" },
     {"Sudoku", "sudoku", "/usr/share/icons/hicolor/32x32/apps/sudoku.png" },
     {"Warmux", "warmux", "/usr/share/pixmaps/warmux_128x128.png" },
     {"Warmux folder for replays, teams and maps", "xdg-open \".local/share/wormux\"", "/usr/share/icons/gnome/16x16/places/folder.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Blender", "blender", "/usr/share/icons/hicolor/16x16/apps/blender.png" },
     {"Dia Diagram Editor", "dia ", "/usr/share/icons/hicolor/16x16/apps/dia.png" },
     {"DjView4", "djview4 ", "/usr/share/icons/hicolor/32x32/apps/djvulibre-djview4.png" },
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"FontForge", "fontforge ", "/usr/share/icons/hicolor/16x16/apps/fontforge.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Gcolor2", "gcolor2", "///usr/share/pixmaps/gcolor2/icon.png" },
     {"Geeqie", "geeqie -r ", "/usr/share/pixmaps/geeqie.png" },
     {"Hugin Batch Processor", "PTBatcherGUI ", "/usr/share/pixmaps/ptbatcher.png" },
     {"Hugin Calibrate Lens", "calibrate_lens_gui", "/usr/share/pixmaps/hugin.png" },
     {"Hugin Panorama Creator", "hugin", "/usr/share/pixmaps/hugin.png" },
     {"IOGraph", "/usr/bin/iograph", "///usr/share/pixmaps/iograph.png" },
     {"Image Viewer", "eog ", "/usr/share/icons/hicolor/16x16/apps/eog.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Lux", "luxrender", "///usr/share/pixmaps/luxrender.svg" },
     {"MeshLab", "meshlab", "///usr/share/pixmaps/meshlab.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Shotwell", "shotwell ", "/usr/share/icons/hicolor/16x16/apps/shotwell.svg" },
     {"feh", "feh ", "///usr/share/feh/images/feh.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Google Earth", "/opt/google/earth/free/google-earth ", "/usr/share/icons/hicolor/16x16/apps/google-earth.png" },
     {"HipChat 2.0", "/opt/HipChat/bin/hipchat", "/usr/share/icons/hicolor/16x16/apps/hipchat.png" },
     {"KRDC", "krdc -caption KRDC "},
     {"Links", "xlinks -g", "/usr/share/pixmaps/links_32x32.xpm" },
     {"Navicat Lite", "/usr/bin/navicat", "///opt/navicat/Navicat/help/img/icon_navicat.png" },
     {"Opera", "/usr/bin/opera ", "/usr/share/icons/hicolor/16x16/apps/opera-browser.png" },
     {"Qtransmission Bittorrent Client", "transmission-qt ", "/usr/share/pixmaps/transmission-qt.png" },
     {"Skype", "skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"TeamViewer 9", "/opt/teamviewer9/tv_bin/script/teamviewer", "///opt/teamviewer9/tv_bin/desktop/teamviewer.png" },
     {"Thunderbird", "thunderbird ", "/usr/share/icons/hicolor/16x16/apps/thunderbird.png" },
     {"X11VNC Server", "x11vnc -gui tray=setpass -rfbport PROMPT -bg -o %HOME/.x11vnc.log.%VNCDISPLAY", "/usr/share/icons/gnome/16x16/devices/computer.png" },
     {"gFTP", "gftp ", "/usr/share/pixmaps/gftp.png" },
     {"iptux", "iptux", "/usr/share/icons/hicolor/16x16/apps/ip-tux.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Adobe Reader 9", "acroread ", "/usr/share/pixmaps/acroread.png" },
     {"Calligra Author", "calligraauthor ", "/usr/share/icons/hicolor/16x16/apps/calligraauthor.png" },
     {"Calligra Flow", "calligraflow ", "/usr/share/icons/hicolor/16x16/apps/calligraflow.png" },
     {"Calligra Words", "calligrawords ", "/usr/share/icons/hicolor/16x16/apps/calligrawords.png" },
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"KchmViewer", "kchmviewer ", "/usr/share/pixmaps/kchmviewer.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"PDF-Shuffler", "pdfshuffler", "/usr/share/pixmaps/pdfshuffler.png" },
     {"StarDict", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"Wordview Microsoft doc Viewer", "wordview", "/usr/share/pixmaps/wordview.xpm" },
     {"Zathura", "zathura "},
     {"apvlv", "apvlv "},
     {"llpp", "llpp "},
 }

 local menu6311ae17c1ee52b36e68aaf4ad066387 = {
     {"TigerVNC viewer", "/usr/bin/vncviewer", "/usr/share/icons/hicolor/16x16/apps/tigervnc.png" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Anjuta", "anjuta ", "/usr/share/icons/hicolor/16x16/apps/anjuta.png" },
     {"Bless Hex Editor", "bless ", "/usr/share/pixmaps/bless-48x48.png" },
     {"CMake", "cmake-gui ", "/usr/share/pixmaps/CMakeSetup32.png" },
     {"Data Display Debugger", "ddd", "/usr/share/pixmaps/ddd.xpm" },
     {"Database browser", "gda-browser-5.0", "/usr/share/pixmaps/gda-browser-5.0.png" },
     {"Devhelp", "devhelp", "/usr/share/icons/hicolor/16x16/apps/devhelp.png" },
     {"Eclipse", "eclipse"},
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/16x16/apps/fluid.png" },
     {"GHex", "ghex ", "/usr/share/icons/hicolor/16x16/apps/ghex.png" },
     {"GNU Octave", "xterm -e /usr/bin/octave", "///usr/share/octave/3.6.4/imagelib/octave-logo.svg" },
     {"Git Cola", "git-cola --prompt", "///usr/share/git-cola/icons/git.svg" },
     {"Git DAG", "git-dag --prompt", "///usr/share/git-cola/icons/git.svg" },
     {"Glade", "glade ", "/usr/share/icons/hicolor/16x16/apps/glade.png" },
     {"Hopper Disassembler", "/usr/bin/hopper", "/usr/share/icons/hicolor/16x16/apps/hopper-disassembler.png" },
     {"IPython Qt console", "ipython qtconsole", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"IPython2 Qt console", "ipython2 qtconsole", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"Meld", "meld ", "/usr/share/icons/hicolor/16x16/apps/meld.png" },
     {"MySQL Workbench", "mysql-workbench", "/usr/share/icons/hicolor/16x16/apps/mysql-workbench.png" },
     {"OpenJDK Monitoring & Management Console", "/usr/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"OpenJDK Policy Tool", "/usr/bin/policytool", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"PyCharm", "/usr/bin/pycharm", "/usr/share/pixmaps/pycharm.png" },
     {"QGit", "/usr/bin/qgit", "/usr/share/pixmaps/qgit.png" },
     {"Qt Assistant", "/usr/lib/qt/bin/assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Creator", "/usr/bin/qtcreator", "///usr/share/icons/hicolor/512x512/apps/QtProject-qtcreator.png" },
     {"Qt Designer", "/usr/lib/qt/bin/designer", "/usr/share/icons/hicolor/128x128/apps/designer.png" },
     {"Qt Linguist", "/usr/lib/qt/bin/linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "/usr/lib/qt/bin/qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"SmartGit/Hg", "smartgithg", "///opt/smartgithg/bin/smartgithg-256.png" },
     {"bpython", "xterm -e /usr/bin/bpython"},
     {"bpython2", "xterm -e /usr/bin/bpython2"},
     {"gitg", "gitg ", "/usr/share/icons/hicolor/16x16/apps/gitg.png" },
     {"ipython", "xterm -e ipython", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"ipython2", "xterm -e ipython2", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
 }

 local menu80d754c83abbbd4ef5d150904efcc86c = {
     {"GNU Octave", "xterm -e /usr/bin/octave", "///usr/share/octave/3.6.4/imagelib/octave-logo.svg" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Audacity", "audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Audio Mixer", "xfce4-mixer", "/usr/share/icons/hicolor/16x16/apps/multimedia-volume-control.png" },
     {"Banshee Media Player", "banshee --redirect-log --play-enqueued ", "/usr/share/icons/hicolor/16x16/apps/media-player-banshee.png" },
     {"Cheese", "cheese", "/usr/share/icons/hicolor/16x16/apps/cheese.png" },
     {"EasyTAG", "easytag ", "/usr/share/icons/hicolor/16x16/apps/easytag.png" },
     {"Gnome Subtitles", "gnome-subtitles ", "/usr/share/pixmaps/gnome-subtitles.svg" },
     {"HDSPConf", "hdspconf", "/usr/share/pixmaps/hdspconf.png" },
     {"HDSPMixer", "hdspmixer", "/usr/share/pixmaps/hdspmixer.png" },
     {"MPlayer", "mplayer "},
     {"MuseScore", "mscore"},
     {"Noise", "noise ", "/usr/share/icons/hicolor/16x16/apps/multimedia-audio-player.svg" },
     {"OSD Lyrics", "osdlyrics", "/usr/local/share/icons/hicolor/64x64/apps/osdlyrics.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/hicolor/16x16/apps/multimedia-volume-control.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"SMPlayer", "smplayer ", "/usr/share/icons/hicolor/16x16/apps/smplayer.png" },
     {"Subtitle Editor", "subtitleeditor ", "/usr/share/icons/hicolor/16x16/apps/subtitleeditor.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"Wavesurfer", "/usr/lib/wavesurfer/src/app-wavesurfer/wavesurfer.tcl", "///usr/lib/wavesurfer/icons/icon48.xpm" },
     {"XMMS", "xmms", "/usr/share/pixmaps/xmms.png" },
     {"avidemux (Qt)", "avidemux2_qt4", "/usr/share/pixmaps/avidemux.png" },
     {"gtk-recordMyDesktop", "gtk-recordMyDesktop", "/usr/share/pixmaps/gtk-recordmydesktop.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"Compiz Fusion Icon", "fusion-icon", "/usr/share/icons/hicolor/22x22/apps/fusion-icon.png" },
     {"Configuration Editor", "gconf-editor", "/usr/share/icons/hicolor/16x16/apps/gconf-editor.png" },
     {"Fcitx", "fcitx", "/usr/share/icons/hicolor/16x16/apps/fcitx.png" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"GSmartControl", "/usr/bin/gsmartcontrol", "/usr/share/icons/hicolor/16x16/apps/gsmartcontrol.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KSysGuard", "ksysguard ", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Nepomuk Backup", "nepomukbackup"},
     {"Nepomuk Cleaner", "nepomukcleaner"},
     {"Network Tools", "gnome-nettool", "/usr/share/icons/hicolor/16x16/apps/gnome-nettool.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"PathFinder", "PathFinder", "/usr/share/pixmaps/PathFinder.png" },
     {"ROXTerm", "roxterm"},
     {"Sakura", "sakura", "/usr/share/pixmaps/terminal-tango.svg" },
     {"SpaceFM", "spacefm ", "/usr/share/icons/hicolor/48x48/apps/spacefm.png" },
     {"Terminator", "terminator", "/usr/share/icons/hicolor/16x16/apps/terminator.png" },
     {"Thunar File Manager", "thunar ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"UNetbootin", "/usr/bin/unetbootin", "/usr/share/icons/hicolor/16x16/apps/unetbootin.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Vifm", "xterm -e vifm ", "/usr/share/pixmaps/vifm.png" },
     {"Wireshark", "wireshark ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Xfce Terminal", "xfce4-terminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Xfe", "xfe", "/usr/share/pixmaps/xfe.png" },
     {"dconf Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
     {"gtk2fontsel", "gtk2fontsel"},
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
 }

xdgmenu = {
    {"Accessibility", menue0e4fc6213e8b3593495a7260c3a4c2e},
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Other", menu6311ae17c1ee52b36e68aaf4ad066387},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Science & Math", menu80d754c83abbbd4ef5d150904efcc86c},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

